### ISSUE TITLE
[Feature Request] Quickfix like navigation from headers to markdown line.

### ISSUE THREAD

**Issue by cirosantilli** [wikimatze/tocdown#5]
Is is possible to somehow jump from a line in the headers window back to the corresponding header line with this plugin? 

With quickfix I can do that without plugins, but the only problem is that the output is too ugly. Do you know how to get around that?

Example:

```
:grep '^#' %
:tab copen
```

Opens something like:

```
apt-get.md|3 col 1| #Ubuntu package model
apt-get.md|7 col 1| #Source types
apt-get.md|20 col 1| ##Pre-installed
apt-get.md|26 col 1| ##Main
apt-get.md|32 col 1| #Software version
```

and if you hit enter it jumps to the right line on the markdown file.

If only we could hide the `apt-get.md|3 col 1| #` noise.

If I am able to do this I will merge it into https://github.com/plasticboy/vim-markdown

**Comment by cirosantilli** [comment]
Ah, same question on SO: http://stackoverflow.com/questions/11199068/how-to-format-vim-quickfix-entry/11202758#11202758 seems it is not possible out of the box. Might just have to hack it with `s` or `conceal`.

**Comment by cirosantilli** [comment]
Ok implemented at: https://github.com/plasticboy/vim-markdown/pull/71/files

**Comment by wikimatze** [comment]
I will play around the vim-markdown plugin and if it does what you mentioned on your stackoverflow plugin, I will update the documentation of this plugin and point to this plugin which does more than just creating a toc.

Thanks for giving feedback and solving the problem.
